const DAY_MS = 24 * 60 * 60 * 1000;
const dateOffset = (days: number) => new Date(Date.now() + days * DAY_MS);

export const moduleStats = [
  { label: "Open Work Orders", value: "18", delta: "5 due today", tone: "coral" },
  { label: "SLA Compliance", value: "94.7%", delta: "+3.2% vs last month", tone: "leaf" },
  { label: "Critical Assets Online", value: "98.9%", delta: "2 assets under watch", tone: "lagoon" },
  { label: "Inventory Value", value: "SAR 2.8M", delta: "3 low-stock SKUs", tone: "sun" },
];

export const chartData = [
  { name: "Jan", ppm: 420, reactive: 180, inspections: 112 },
  { name: "Feb", ppm: 470, reactive: 154, inspections: 140 },
  { name: "Mar", ppm: 510, reactive: 132, inspections: 156 },
  { name: "Apr", ppm: 548, reactive: 121, inspections: 169 },
  { name: "May", ppm: 590, reactive: 118, inspections: 182 },
  { name: "Jun", ppm: 626, reactive: 96, inspections: 201 },
];

export const assetHealth = [
  { name: "Excellent", value: 42 },
  { name: "Good", value: 31 },
  { name: "Monitor", value: 18 },
  { name: "Risk", value: 9 },
];

export const fallbackData = {
  sites: [
    { id: "site-riyadh-kafd", name: "King Abdullah Financial District", city: "Riyadh", country: "Saudi Arabia", type: "Mixed Use", areaSqm: 284000 },
    { id: "site-jazan-camp", name: "Jazan Operations Camp", city: "Jazan", country: "Saudi Arabia", type: "Housing / Industrial Support", areaSqm: 86000 },
  ],
  assets: [
    {
      id: "asset-ahu-004",
      tag: "AHU-RYD-01-004",
      name: "Air Handling Unit 4",
      category: "HVAC",
      system: "Cooling",
      criticality: "HIGH",
      status: "ACTIVE",
      serialNumber: "AHU-RYD-01-004-SN",
      siteCode: "169",
      zone: "CB",
      buildingCode: "CB04",
      assetGroup: "AHU",
      assetDescription: "Primary office floor air handling unit",
      additionalDescription: "Serves executive offices and meeting rooms",
      parentAsset: "HVAC-PLANT",
      departmentCode: "MEP",
      assignedTeamCode: "MEP",
      assignedSupervisorEmail: "mariam@brightworks.local",
      remarks: "Filter bank nearing replacement threshold.",
      manufacturer: "Enterprise OEM",
      model: "X-Series",
      installDate: dateOffset(-1200),
      replacementDate: dateOffset(2200),
      warrantyExpiry: dateOffset(545),
      contractRef: "Integrated Hard Services Contract",
      documentationUrl: "https://example.com/asset-manual.pdf",
      purchaseCost: 145000,
      salvageValue: 14500,
      depreciationRate: 12.5,
      conditionScore: 88,
      floor: "18",
      room: "Plant Room",
      qrCode: "CAFM-ASSET:AHU-RYD-01-004",
      site: { name: "King Abdullah Financial District" },
      building: { name: "Tower A", code: "KAFD-A" },
      workOrders: [{ woNo: "WO-81024", title: "Replace AHU filters and rebalance", status: "IN_PROGRESS", updatedAt: dateOffset(-1), inventoryUsed: "FLT-24X24-MERV13:2", workNotes: "Isolation completed." }],
      history: [{ id: "hist-ahu-1", eventType: "COMMISSIONED", title: "Asset commissioned", actor: "System", details: "Baseline condition score loaded.", createdAt: dateOffset(-1200) }],
    },
    { id: "asset-gen-001", tag: "GEN-RYD-02-001", name: "Emergency Generator 1", category: "ELEC", system: "Electrical", criticality: "CRITICAL", status: "STANDBY", conditionScore: 91, purchaseCost: 420000, floor: "B2", room: "Generator Room", departmentCode: "ELEC", assignedTeamCode: "ELEC", manufacturer: "Enterprise OEM", model: "GEN-X", installDate: dateOffset(-980), replacementDate: dateOffset(2600), site: { name: "King Abdullah Financial District" }, building: { name: "Tower A", code: "KAFD-A" }, workOrders: [], history: [] },
    { id: "asset-fls-221", tag: "FLS-RYD-01-221", name: "Fire Pump Controller", category: "FLS", system: "Fire", criticality: "CRITICAL", status: "ACTIVE", conditionScore: 76, purchaseCost: 88000, floor: "B2", room: "Fire Pump Room", departmentCode: "MEP", assignedTeamCode: "MEP", manufacturer: "Enterprise OEM", model: "FLS-C", installDate: dateOffset(-850), replacementDate: dateOffset(1900), site: { name: "King Abdullah Financial District" }, building: { name: "Tower A", code: "KAFD-A" }, workOrders: [], history: [] },
    { id: "asset-chl-002", tag: "CHL-RYD-01-002", name: "Centrifugal Chiller 2", category: "HVAC", system: "Cooling", criticality: "CRITICAL", status: "ACTIVE", conditionScore: 72, purchaseCost: 980000, floor: "B2", room: "Chiller Plant", departmentCode: "MEP", assignedTeamCode: "MEP", manufacturer: "Enterprise OEM", model: "CHL-900", installDate: dateOffset(-1500), replacementDate: dateOffset(1600), site: { name: "King Abdullah Financial District" }, building: { name: "Tower A", code: "KAFD-A" }, workOrders: [], history: [] },
    { id: "asset-lift-008", tag: "LFT-RYD-A-008", name: "Passenger Lift 8", category: "ELEC", system: "Vertical Transport", criticality: "HIGH", status: "ACTIVE", conditionScore: 83, purchaseCost: 360000, floor: "G", room: "Lift Lobby", departmentCode: "ELEC", assignedTeamCode: "ELEC", manufacturer: "Enterprise OEM", model: "LFT-8", installDate: dateOffset(-700), replacementDate: dateOffset(2300), site: { name: "King Abdullah Financial District" }, building: { name: "Tower A", code: "KAFD-A" }, workOrders: [], history: [] },
    { id: "asset-fur-044", tag: "FUR-RYD-18-044", name: "Executive Desk 44", category: "FURN", system: "Furniture", criticality: "LOW", status: "ACTIVE", conditionScore: 95, purchaseCost: 9500, floor: "18", room: "Executive Offices", departmentCode: "CIVIL", assignedTeamCode: "CIVIL", manufacturer: "Workspace Co", model: "EX-DESK", installDate: dateOffset(-360), replacementDate: dateOffset(1800), site: { name: "King Abdullah Financial District" }, building: { name: "Tower A", code: "KAFD-A" }, workOrders: [], history: [] },
    { id: "asset-it-ap12", tag: "IT-RYD-18-AP12", name: "Wireless Access Point 12", category: "IT", system: "Network", criticality: "MEDIUM", status: "ACTIVE", conditionScore: 89, purchaseCost: 2800, floor: "18", room: "Executive Offices", departmentCode: "ELEC", assignedTeamCode: "ELEC", manufacturer: "Network OEM", model: "AP-6", installDate: dateOffset(-250), replacementDate: dateOffset(1000), site: { name: "King Abdullah Financial District" }, building: { name: "Tower A", code: "KAFD-A" }, workOrders: [], history: [] },
    { id: "asset-hsg-ac101", tag: "HSG-A101-AC01", name: "Housing Room A101 Split AC", category: "HVAC", system: "Housing HVAC", criticality: "MEDIUM", status: "ACTIVE", conditionScore: 81, purchaseCost: 6800, floor: "1", room: "A101", departmentCode: "HOUSING", assignedTeamCode: "HSG", manufacturer: "CoolAir", model: "Split-24", installDate: dateOffset(-420), replacementDate: dateOffset(1200), site: { name: "Jazan Operations Camp" }, building: { name: "Housing Block A", code: "HSB-A" }, workOrders: [], history: [] },
  ],
  requests: [
    { id: "req-24001", ticketNo: "SR-24001", title: "Lobby temperature above comfort range", category: "HVAC", departmentCode: "MEP", serviceCode: "HVAC-REQ", assignedTeamCode: "MEP", assignedSupervisorEmail: "mariam@brightworks.local", requester: "Tenant Services", channel: "Portal", priority: "HIGH", status: "ASSIGNED", location: "Tower A > G > Main Lobby", slaHours: 12, dueAt: dateOffset(1), description: "Lobby temperature is above comfort range." },
    { id: "req-24002", ticketNo: "SR-24002", title: "Water leak near pantry", category: "Plumbing", departmentCode: "MEP", serviceCode: "PLUMB-REQ", assignedTeamCode: "MEP", assignedSupervisorEmail: "mariam@brightworks.local", requester: "Floor Warden", channel: "Phone", priority: "CRITICAL", status: "IN_PROGRESS", location: "Tower A > 18 > Pantry", slaHours: 4, dueAt: dateOffset(0), description: "Visible leak under pantry sink." },
    { id: "req-24003", ticketNo: "SR-24003", title: "Access card reader intermittent", category: "Security", departmentCode: "SEC", serviceCode: "SEC-REQ", assignedTeamCode: "ELEC", assignedSupervisorEmail: "mariam@brightworks.local", requester: "Reception", channel: "Helpdesk", priority: "MEDIUM", status: "NEW", location: "Tower A > G > Main Lobby", slaHours: 48, dueAt: dateOffset(2), description: "Reader fails every few swipes." },
    { id: "req-24004", ticketNo: "SR-24004", title: "Ceiling tile damaged in office", category: "Civil", departmentCode: "CIVIL", serviceCode: "CIVIL-REQ", assignedTeamCode: "CIVIL", assignedSupervisorEmail: "omar@brightworks.local", requester: "Admin Office", channel: "Portal", priority: "LOW", status: "APPROVED", location: "Tower A > 18 > Executive Offices", slaHours: 36, dueAt: dateOffset(2), description: "Ceiling tile cracked near workstation row." },
    { id: "req-24005", ticketNo: "SR-24005", title: "Washroom cleaning required", category: "Housekeeping", departmentCode: "HK", serviceCode: "HK-REQ", assignedTeamCode: "HK", assignedSupervisorEmail: "omar@brightworks.local", requester: "Resident", channel: "Mobile", priority: "MEDIUM", status: "NEW", location: "Tower A > 18 > Pantry", slaHours: 8, dueAt: dateOffset(1), description: "Additional cleaning requested after spill." },
    { id: "req-24006", ticketNo: "SR-24006", title: "Housing room A101 AC not cooling", category: "Housing Maintenance", departmentCode: "HOUSING", serviceCode: "HOUSING-MAINT", assignedTeamCode: "HSG", assignedSupervisorEmail: "lina@brightworks.local", requester: "Hamayun Ali", channel: "Reception", priority: "HIGH", status: "PENDING_ASSIGNMENT", location: "Reserve Housing Village / Block A / 1 / A101", slaHours: 6, dueAt: dateOffset(0), description: "Resident reports weak cooling from split AC." },
  ],
  workOrders: [
    { id: "wo-81024", woNo: "WO-81024", title: "Replace AHU filters and rebalance", type: "PPM", priority: "HIGH", status: "IN_PROGRESS", assetId: "asset-ahu-004", departmentCode: "MEP", serviceCode: "HVAC-REQ", assignedTeamCode: "MEP", jobPlanCode: "JP-HVAC-FILTER", assignedToId: "user-adeel", plannedStart: dateOffset(-1), dueAt: dateOffset(1), estimatedHours: 4, actualHours: 1.5, cost: 2200, responseAt: dateOffset(-1), resolutionAt: null, finishedAt: null, inventoryUsed: "FLT-24X24-MERV13:2", workNotes: "Technician responded and AHU isolation is complete.", jobPlan: "Inspect filters, replace, clean frame and verify differential pressure.", safetyNotes: "Use PPE and verify safe access.", assignedTo: { name: "Adeel Khan", email: "adeel@brightworks.local" }, asset: { tag: "AHU-RYD-01-004", name: "Air Handling Unit 4" }, inventoryIssues: [] },
    { id: "wo-81025", woNo: "WO-81025", title: "Fire pump weekly test", type: "Inspection", priority: "CRITICAL", status: "ASSIGNED", assetId: "asset-fls-221", departmentCode: "MEP", serviceCode: "PLUMB-REQ", assignedTeamCode: "MEP", jobPlanCode: "JP-FLS-PUMP", assignedToId: "user-sara", plannedStart: dateOffset(0), dueAt: dateOffset(1), estimatedHours: 2, actualHours: null, cost: 780, responseAt: null, resolutionAt: null, finishedAt: null, inventoryUsed: "", workNotes: "", jobPlan: "Run pump, record pressures and verify alarms.", safetyNotes: "Notify control room before test.", assignedTo: { name: "Sara Malik", email: "sara@brightworks.local" }, asset: { tag: "FLS-RYD-01-221", name: "Fire Pump Controller" }, inventoryIssues: [] },
    { id: "wo-81026", woNo: "WO-81026", title: "Chiller vibration investigation", type: "Condition Based", priority: "HIGH", status: "TRIAGED", assetId: "asset-chl-002", departmentCode: "MEP", serviceCode: "HVAC-REQ", assignedTeamCode: "MEP", jobPlanCode: "JP-CHILLER-CB", assignedToId: "user-adeel", plannedStart: dateOffset(0), dueAt: dateOffset(2), estimatedHours: 4, actualHours: null, cost: 0, responseAt: null, resolutionAt: null, finishedAt: null, inventoryUsed: "", workNotes: "", jobPlan: "Review BMS trend and inspect vibration.", safetyNotes: "Use hearing protection.", assignedTo: { name: "Adeel Khan", email: "adeel@brightworks.local" }, asset: { tag: "CHL-RYD-01-002", name: "Centrifugal Chiller 2" }, inventoryIssues: [] },
    { id: "wo-81027", woNo: "WO-81027", title: "Replace failed LED panel", type: "Corrective", priority: "MEDIUM", status: "PENDING_SUPERVISOR_REVIEW", assetId: "asset-it-ap12", departmentCode: "ELEC", serviceCode: "ELEC-REQ", assignedTeamCode: "ELEC", jobPlanCode: "JP-ELEC-LIGHT", assignedToId: "user-adeel", plannedStart: dateOffset(-2), dueAt: dateOffset(0), estimatedHours: 1, actualHours: 1, cost: 320, responseAt: dateOffset(-2), resolutionAt: dateOffset(-1), finishedAt: null, inventoryUsed: "LED-PNL-60W:1", workNotes: "Panel replaced and tested. Awaiting supervisor closure.", jobPlan: "Isolate circuit and replace panel.", safetyNotes: "Lockout/tagout circuit.", assignedTo: { name: "Adeel Khan", email: "adeel@brightworks.local" }, asset: { tag: "IT-RYD-18-AP12", name: "Wireless Access Point 12" }, inventoryIssues: [] },
    { id: "wo-81028", woNo: "WO-81028", title: "Repair executive office desk drawer", type: "Corrective", priority: "LOW", status: "CLOSED", assetId: "asset-fur-044", departmentCode: "CIVIL", serviceCode: "CIVIL-REQ", assignedTeamCode: "CIVIL", jobPlanCode: "JP-CIVIL-FIX", assignedToId: "user-omar", plannedStart: dateOffset(-5), dueAt: dateOffset(-3), estimatedHours: 2, actualHours: 1.2, cost: 140, responseAt: dateOffset(-5), resolutionAt: dateOffset(-4), finishedAt: dateOffset(-4), inventoryUsed: "", workNotes: "Drawer rails adjusted and work verified.", jobPlan: "Inspect defect and repair fixture.", safetyNotes: "Protect surrounding finishes.", assignedTo: { name: "Omar Siddiqui", email: "omar@brightworks.local" }, asset: { tag: "FUR-RYD-18-044", name: "Executive Desk 44" }, inventoryIssues: [] },
    { id: "wo-81029", woNo: "WO-81029", title: "Restore cooling in housing room A101", type: "Housing Maintenance", priority: "HIGH", status: "OPEN", assetId: "asset-hsg-ac101", departmentCode: "HOUSING", serviceCode: "HOUSING-MAINT", assignedTeamCode: "HSG", jobPlanCode: "JP-HSG-ROOM", assignedToId: "user-faisal", plannedStart: dateOffset(0), dueAt: dateOffset(1), estimatedHours: 3, actualHours: null, cost: 0, responseAt: null, resolutionAt: null, finishedAt: null, inventoryUsed: "", workNotes: "Pending technician dispatch.", jobPlan: "Check thermostat, filter, condensate line and cooling performance.", safetyNotes: "Isolate power before opening indoor unit.", assignedTo: { name: "Faisal Noor", email: "faisal@brightworks.local" }, asset: { tag: "HSG-A101-AC01", name: "Housing Room A101 Split AC" }, request: { ticketNo: "SR-24006", location: "Reserve Housing Village / Block A / 1 / A101" }, inventoryIssues: [] },
  ],
  inventory: [
    { id: "inv-filter", sku: "FLT-24X24-MERV13", name: "MERV 13 Filter", category: "HVAC", unit: "pcs", onHand: 32, reorderPoint: 50, unitCost: 45, vendor: "Gulf MEP Supplies", location: "Central Store A" },
    { id: "inv-led", sku: "LED-PNL-60W", name: "LED Panel 60W", category: "Electrical", unit: "pcs", onHand: 121, reorderPoint: 80, unitCost: 32, vendor: "BrightLine Trading", location: "Central Store A" },
    { id: "inv-valve", sku: "VLV-BALL-2IN", name: "2 inch Ball Valve", category: "Plumbing", unit: "pcs", onHand: 18, reorderPoint: 30, unitCost: 79, vendor: "AquaTech Parts", location: "Central Store B" },
    { id: "inv-battery", sku: "BAT-UPS-12V", name: "UPS Battery 12V", category: "Electrical", unit: "pcs", onHand: 12, reorderPoint: 16, unitCost: 210, vendor: "PowerSafe Trading", location: "Electrical Store" },
    { id: "inv-door", sku: "DR-HINGE-SS", name: "Stainless Door Hinge", category: "Civil", unit: "set", onHand: 7, reorderPoint: 20, unitCost: 28, vendor: "BuildRight Supplies", location: "Civil Store" },
  ],
  inspections: [
    { id: "ins-fls", code: "INS-FLS-144", title: "Fire life safety weekly audit", area: "All Towers", inspector: "Sara Malik", risk: "HIGH", score: 91, status: "COMPLETED", dueAt: dateOffset(1), findings: "Minor signage issue in stairwell 3." },
    { id: "ins-hse", code: "INS-HSE-033", title: "Contractor permit compliance", area: "Basement Plant", inspector: "Mariam Al-Fahad", risk: "MODERATE", score: 84, status: "IN_PROGRESS", dueAt: dateOffset(1), findings: "Two permits pending supervisor closure." },
    { id: "ins-housekeeping", code: "INS-HK-050", title: "Public washroom housekeeping audit", area: "Tower A Level 18", inspector: "Omar Siddiqui", risk: "LOW", score: 88, status: "OPEN", dueAt: dateOffset(3), findings: "Verify consumables and odor control." },
  ],
  complianceCertificates: [
    { id: "cert-fls", certificateNo: "CERT-FLS-2026-001", title: "Fire Alarm Civil Defense Certificate", authority: "Civil Defense", category: "Life Safety", assetTag: "FLS-RYD-01-221", location: "Tower A", owner: "HSE Manager", issueDate: dateOffset(-320), expiryDate: dateOffset(45), status: "ACTIVE", risk: "HIGH", renewalLeadDays: 30, evidenceUrl: "", notes: "Annual Civil Defense certificate with renewal required before expiry." },
    { id: "cert-lift", certificateNo: "CERT-LIFT-2026-004", title: "Elevator Third Party Inspection", authority: "TUV", category: "Vertical Transport", assetTag: "LFT-RYD-A-008", location: "Tower A", owner: "Facilities Supervisor", issueDate: dateOffset(-90), expiryDate: dateOffset(12), status: "EXPIRING_SOON", risk: "MODERATE", renewalLeadDays: 30, evidenceUrl: "", notes: "Third-party inspection due for renewal this month." },
    { id: "cert-gen", certificateNo: "CERT-GEN-2026-002", title: "Emergency Generator Load Test Certificate", authority: "Authorized Testing Body", category: "Electrical", assetTag: "GEN-RYD-02-001", location: "Generator Room", owner: "Electrical Supervisor", issueDate: dateOffset(-180), expiryDate: dateOffset(120), status: "ACTIVE", risk: "HIGH", renewalLeadDays: 45, evidenceUrl: "", notes: "Quarterly generator load bank certificate and evidence file." },
    { id: "cert-water", certificateNo: "CERT-WTR-2026-007", title: "Potable Water Tank Cleaning Certificate", authority: "Approved Lab", category: "Water Hygiene", assetTag: "WTR-RYD-RO-001", location: "Tower A Roof", owner: "MEP Supervisor", issueDate: dateOffset(-370), expiryDate: dateOffset(-5), status: "EXPIRED", risk: "EXTREME", renewalLeadDays: 30, evidenceUrl: "", notes: "Immediate renewal required before next audit." },
  ],
  alerts: [
    { id: "alert-chiller", source: "BMS", assetTag: "CHL-RYD-01-002", severity: "HIGH", message: "Chiller vibration exceeds baseline by 18%", status: "TRIAGED", detectedAt: dateOffset(-1) },
    { id: "alert-energy", source: "Energy Meter", assetTag: "MDB-RYD-03-001", severity: "MEDIUM", message: "Peak demand forecast breach in 48 hours", status: "NEW", detectedAt: dateOffset(0) },
    { id: "alert-housing", source: "Room Sensor", assetTag: "HSG-A101-AC01", severity: "HIGH", message: "Housing room A101 temperature above setpoint for 3 hours", status: "NEW", detectedAt: dateOffset(0) },
  ],
  teams: [
    { id: "team-mep", code: "MEP", name: "MEP Response Team", type: "Hard Services", supervisor: "Adeel Khan", phone: "+966 500000001", email: "mep@reserve.local", shift: "24/7", coverage: "MEP", services: [] },
    { id: "team-elec", code: "ELEC", name: "Electrical Response Team", type: "Hard Services", supervisor: "Mariam Al-Fahad", phone: "+966 500000002", email: "electrical@reserve.local", shift: "Day + On-call", coverage: "ELEC", services: [] },
    { id: "team-civil", code: "CIVIL", name: "Civil & Fitout Team", type: "Soft / Civil Services", supervisor: "Omar Siddiqui", phone: "+966 500000003", email: "civil@reserve.local", shift: "Day shift", coverage: "CIVIL", services: [] },
    { id: "team-hk", code: "HK", name: "Housekeeping Team", type: "Soft Services", supervisor: "Omar Siddiqui", phone: "+966 500000004", email: "housekeeping@reserve.local", shift: "Two shifts", coverage: "HK", services: [] },
    { id: "team-hsg", code: "HSG", name: "Housing Operations Team", type: "Accommodation Services", supervisor: "Lina Haddad", phone: "+966 500000005", email: "housing@reserve.local", shift: "24/7 reception + day maintenance", coverage: "HOUSING", services: [] },
  ],
  services: [
    { id: "svc-hvac", code: "HVAC-REQ", name: "HVAC Complaint", category: "HVAC", type: "Reactive", priority: "HIGH", slaHours: 12, teamId: "team-mep", team: { code: "MEP", name: "MEP Response Team" }, description: "Temperature, ventilation and indoor air quality requests." },
    { id: "svc-elec", code: "ELEC-REQ", name: "Electrical Fault", category: "Electrical", type: "Reactive", priority: "HIGH", slaHours: 8, teamId: "team-elec", team: { code: "ELEC", name: "Electrical Response Team" }, description: "Lighting, socket, panel and breaker faults." },
    { id: "svc-plumb", code: "PLUMB-REQ", name: "Plumbing Leak", category: "Plumbing", type: "Reactive", priority: "CRITICAL", slaHours: 4, teamId: "team-mep", team: { code: "MEP", name: "MEP Response Team" }, description: "Leaks, blockages and water system faults." },
    { id: "svc-civil", code: "CIVIL-REQ", name: "Civil Repair", category: "Civil", type: "Reactive", priority: "MEDIUM", slaHours: 24, teamId: "team-civil", team: { code: "CIVIL", name: "Civil & Fitout Team" }, description: "Doors, ceilings, finishes and furniture defects." },
    { id: "svc-hk", code: "HK-REQ", name: "Housekeeping Request", category: "Housekeeping", type: "Service", priority: "LOW", slaHours: 12, teamId: "team-hk", team: { code: "HK", name: "Housekeeping Team" }, description: "Cleaning, waste removal and pantry services." },
    { id: "svc-sec", code: "SEC-REQ", name: "Access Control", category: "Security", type: "Reactive", priority: "MEDIUM", slaHours: 12, teamId: "team-elec", team: { code: "ELEC", name: "Electrical Response Team" }, description: "Access reader and door lock support." },
    { id: "svc-housing", code: "HOUSING-MAINT", name: "Housing Maintenance", category: "Housing Maintenance", type: "Reactive", priority: "HIGH", slaHours: 6, teamId: "team-hsg", team: { code: "HSG", name: "Housing Operations Team" }, description: "Resident accommodation room and camp maintenance." },
  ],
  categories: [
    { id: "cat-hvac", code: "HVAC", name: "HVAC Equipment", type: "MEP", defaultLifeYrs: 15, statutory: false, description: "Cooling, heating and ventilation equipment." },
    { id: "cat-elec", code: "ELEC", name: "Electrical Equipment", type: "Electrical", defaultLifeYrs: 20, statutory: false, description: "Panels, DBs, UPS, lighting and generators." },
    { id: "cat-plumb", code: "PLUMB", name: "Plumbing Equipment", type: "Plumbing", defaultLifeYrs: 15, statutory: false, description: "Pumps, tanks, valves and water assets." },
    { id: "cat-fls", code: "FLS", name: "Fire & Life Safety", type: "Life Safety", defaultLifeYrs: 12, statutory: true, description: "Fire pumps, panels and emergency systems." },
    { id: "cat-furn", code: "FURN", name: "Furniture & Fixtures", type: "Civil", defaultLifeYrs: 10, statutory: false, description: "Furniture, fixtures and room equipment." },
    { id: "cat-it", code: "IT", name: "IT Infrastructure", type: "IT", defaultLifeYrs: 7, statutory: false, description: "Network racks, access points and CCTV devices." },
  ],
  ppms: [
    { id: "ppm-hvac", code: "PM-HVAC-001", name: "Monthly AHU Service", assetTag: "AHU-RYD-01-004", frequency: "Monthly", nextDue: dateOffset(7), durationHrs: 2, checklist: "Check belts, filters, coils, dampers and vibration.", active: true },
    { id: "ppm-fls", code: "PM-FLS-010", name: "Weekly Fire Pump Test", assetTag: "FLS-RYD-01-221", frequency: "Weekly", nextDue: dateOffset(3), durationHrs: 1.5, checklist: "Run pump, verify pressures, alarms and valves.", active: true },
    { id: "ppm-gen", code: "PM-GEN-003", name: "Generator Load Run", assetTag: "GEN-RYD-02-001", frequency: "Monthly", nextDue: dateOffset(9), durationHrs: 2, checklist: "Inspect fuel, batteries, coolant, ATS and run under load.", active: true },
    { id: "ppm-lift", code: "PM-LIFT-008", name: "Lift Safety Inspection", assetTag: "LFT-RYD-A-008", frequency: "Quarterly", nextDue: dateOffset(18), durationHrs: 3, checklist: "Check door operation, emergency phone, ride quality and rescue kit.", active: true },
    { id: "ppm-hsg-ac", code: "PM-HSG-AC101", name: "Housing AC Preventive Service", assetTag: "HSG-A101-AC01", frequency: "Monthly", nextDue: dateOffset(6), durationHrs: 1.5, checklist: "Clean filters, check drain and verify cooling.", active: true },
  ],
  users: [
    { id: "user-admin", name: "System Administrator", email: "admin@cafm.local", role: "Admin", department: "Administration", active: true, team: null },
    { id: "user-mariam", name: "Mariam Al-Fahad", email: "mariam@brightworks.local", role: "Facility Director", department: "Operations", active: true, team: null },
    { id: "user-omar", name: "Omar Siddiqui", email: "omar@brightworks.local", role: "Helpdesk Manager", department: "Tenant Services", active: true, team: null },
    { id: "user-adeel", name: "Adeel Khan", email: "adeel@brightworks.local", role: "Technician", department: "MEP", active: true, team: { code: "MEP" } },
    { id: "user-sara", name: "Sara Malik", email: "sara@brightworks.local", role: "Technician", department: "Life Safety", active: true, team: { code: "MEP" } },
    { id: "user-lina", name: "Lina Haddad", email: "lina@brightworks.local", role: "Supervisor", department: "HOUSING", active: true, team: { code: "HSG" } },
    { id: "user-faisal", name: "Faisal Noor", email: "faisal@brightworks.local", role: "Technician", department: "HOUSING", active: true, team: { code: "HSG" } },
  ],
  permissions: [
    { id: "perm-assets-manage", code: "assets.manage", name: "Manage Assets", module: "Assets", description: "Create, edit, import and view asset history" },
    { id: "perm-assets-view", code: "assets.view", name: "View Assets", module: "Assets", description: "View asset register, history and location drill-down" },
    { id: "perm-work-manage", code: "work.manage", name: "Manage Work Orders", module: "Work", description: "Create and update work orders" },
    { id: "perm-work-execute", code: "work.execute", name: "Execute Work Orders", module: "Work", description: "Update status, time, photos and material usage" },
    { id: "perm-work-view", code: "work.view", name: "View Work Orders", module: "Work", description: "View work order panels and completion history" },
    { id: "perm-work-assign", code: "work.assign", name: "Assign Work Orders", module: "Work", description: "Assign work orders to technicians or teams" },
    { id: "perm-work-verify", code: "work.verify", name: "Verify Completed Work", module: "Work", description: "Approve, reject, reopen or close completed work" },
    { id: "perm-requests-manage", code: "requests.manage", name: "Manage Service Requests", module: "Helpdesk", description: "Create, edit, assign and convert requests" },
    { id: "perm-requests-approve", code: "requests.approve", name: "Approve or Reject Requests", module: "Helpdesk", description: "Supervisor review and validate service requests" },
    { id: "perm-requests-view", code: "requests.view", name: "View Service Requests", module: "Helpdesk", description: "View assigned service requests" },
    { id: "perm-ppm", code: "ppm.manage", name: "Manage PPM", module: "Maintenance", description: "Create planned preventive maintenance schedules" },
    { id: "perm-users", code: "users.manage", name: "Manage Users", module: "Administration", description: "Create users and assign roles" },
    { id: "perm-roles", code: "roles.manage", name: "Manage Roles", module: "Administration", description: "Create custom roles and permission sets" },
    { id: "perm-reports", code: "reports.view", name: "View Reports", module: "Reports", description: "Preview and download reports" },
    { id: "perm-housing-manage", code: "housing.manage", name: "Manage Housing Operations", module: "Housing", description: "Create and manage accommodation records" },
    { id: "perm-housing-approve", code: "housing.approve", name: "Approve Housing Requests", module: "Housing", description: "Approve or reject housing bookings" },
    { id: "perm-housing-view", code: "housing.view", name: "View Housing", module: "Housing", description: "View housing dashboards and reports" },
    { id: "perm-compliance-manage", code: "compliance.manage", name: "Manage Compliance & Certification", module: "Compliance", description: "Create and renew statutory certificates" },
    { id: "perm-compliance-view", code: "compliance.view", name: "View Compliance & Certification", module: "Compliance", description: "View compliance dashboards and alerts" },
  ],
  departments: [
    { id: "dept-mep", code: "MEP", name: "MEP Department", siteLocation: "Tower A", description: "Mechanical, electrical and plumbing services." },
    { id: "dept-elec", code: "ELEC", name: "Electrical Department", siteLocation: "Tower A", description: "Power distribution, lighting, UPS, generators and panels." },
    { id: "dept-civil", code: "CIVIL", name: "Civil Department", siteLocation: "Tower A", description: "Fitout, finishes, rooms and small civil repairs." },
    { id: "dept-hk", code: "HK", name: "Housekeeping Department", siteLocation: "Tower A", description: "Cleaning, waste and public area upkeep." },
    { id: "dept-sec", code: "SEC", name: "Security Department", siteLocation: "Tower A", description: "Access control and security equipment coordination." },
    { id: "dept-housing", code: "HOUSING", name: "Housing Operations", siteLocation: "Jazan Operations Camp", description: "Accommodation, occupancy, room readiness and resident services." },
  ],
  employees: [
    { id: "emp-001", name: "Adeel Khan", email: "adeel.employee@brightworks.local", companyId: "EMP-001", nationalityType: "Resident", departmentCode: "MEP", siteLocation: "Tower A" },
    { id: "emp-002", name: "Sara Malik", email: "sara.employee@brightworks.local", companyId: "EMP-002", nationalityType: "Saudi", departmentCode: "FLS", siteLocation: "Tower A" },
    { id: "emp-003", name: "Faisal Noor", email: "faisal.employee@brightworks.local", companyId: "EMP-003", nationalityType: "Resident", departmentCode: "HOUSING", siteLocation: "Jazan Operations Camp" },
    { id: "emp-004", name: "Lina Haddad", email: "lina.employee@brightworks.local", companyId: "EMP-004", nationalityType: "Saudi", departmentCode: "HOUSING", siteLocation: "Jazan Operations Camp" },
    { id: "emp-005", name: "Ravi Thomas", email: "ravi.employee@brightworks.local", companyId: "EMP-005", nationalityType: "Resident", departmentCode: "HK", siteLocation: "Tower A" },
  ],
  rolePermissions: [
    { id: "rp-admin-assets", role: "Admin", permissionId: "perm-assets-manage", permission: { code: "assets.manage", name: "Manage Assets", module: "Assets", description: "Create and edit assets" } },
    { id: "rp-admin-housing", role: "Admin", permissionId: "perm-housing-manage", permission: { code: "housing.manage", name: "Manage Housing Operations", module: "Housing", description: "Create and manage accommodation records" } },
    { id: "rp-supervisor-work", role: "Supervisor", permissionId: "perm-work-manage", permission: { code: "work.manage", name: "Manage Work Orders", module: "Work", description: "Create and update work orders" } },
    { id: "rp-tech-execute", role: "Technician", permissionId: "perm-work-execute", permission: { code: "work.execute", name: "Execute Work Orders", module: "Work", description: "Update assigned work" } },
    { id: "rp-readonly-reports", role: "Read-only", permissionId: "perm-reports", permission: { code: "reports.view", name: "View Reports", module: "Reports", description: "Preview reports" } },
  ],
  roles: [
    { id: "role-admin", name: "Admin", description: "Full system administration", standard: true },
    { id: "role-supervisor", name: "Supervisor", description: "Assign and supervise work", standard: true },
    { id: "role-technician", name: "Technician", description: "Execute and update assigned work", standard: true },
    { id: "role-helpdesk", name: "Helpdesk", description: "Request intake and triage", standard: true },
    { id: "role-readonly", name: "Read-only", description: "View reports and registers", standard: true },
  ],
  locations: [
    { id: "loc-lobby", code: "KAFD-A-G-LOBBY", site: "King Abdullah Financial District", zone: "CB", building: "Tower A", floor: "G", room: "Main Lobby", type: "Public", description: "Main reception and visitor lobby.", active: true },
    { id: "loc-plant", code: "KAFD-A-18-PLANT", site: "King Abdullah Financial District", zone: "CB", building: "Tower A", floor: "18", room: "Plant Room", type: "Plant", description: "Primary MEP plant room.", active: true },
    { id: "loc-office", code: "KAFD-A-18-OFFICE", site: "King Abdullah Financial District", zone: "CB", building: "Tower A", floor: "18", room: "Executive Offices", type: "Office", description: "Executive office suite and meeting rooms.", active: true },
    { id: "loc-gen", code: "KAFD-A-B2-GEN", site: "King Abdullah Financial District", zone: "CB", building: "Tower A", floor: "B2", room: "Generator Room", type: "Plant", description: "Emergency generator room.", active: true },
    { id: "loc-fire", code: "KAFD-A-B2-FIRE", site: "King Abdullah Financial District", zone: "CB", building: "Tower A", floor: "B2", room: "Fire Pump Room", type: "Life Safety", description: "Fire pump and controller room.", active: true },
    { id: "loc-housing-a101", code: "HSP-A-1-A101", site: "Jazan Operations Camp", zone: "Housing", building: "Block A", floor: "1", room: "A101", type: "Accommodation", description: "Single executive housing room.", active: true },
  ],
  jobPlans: [
    { id: "jp-hvac", code: "JP-HVAC-FILTER", name: "AHU Filter Replacement", assetType: "HVAC", departmentCode: "MEP", serviceCode: "HVAC-REQ", estimatedHours: 2, priority: "MEDIUM", steps: "Inspect filter bank, isolate AHU if required, replace filters, clean frame and verify pressure.", safetyNotes: "Use PPE and safe access.", active: true },
    { id: "jp-fls", code: "JP-FLS-PUMP", name: "Fire Pump Weekly Test", assetType: "FLS", departmentCode: "MEP", serviceCode: "PLUMB-REQ", estimatedHours: 1.5, priority: "CRITICAL", steps: "Check controller, run pump and record pressure.", safetyNotes: "Notify control room before testing.", active: true },
    { id: "jp-chiller", code: "JP-CHILLER-CB", name: "Chiller Condition Investigation", assetType: "HVAC", departmentCode: "MEP", serviceCode: "HVAC-REQ", estimatedHours: 4, priority: "HIGH", steps: "Review BMS trend, inspect vibration and record recommendation.", safetyNotes: "Use hearing protection.", active: true },
    { id: "jp-elec", code: "JP-ELEC-LIGHT", name: "Lighting Panel Replacement", assetType: "ELEC", departmentCode: "ELEC", serviceCode: "ELEC-REQ", estimatedHours: 1, priority: "MEDIUM", steps: "Isolate circuit, replace fitting and test lux level.", safetyNotes: "Lockout/tagout circuit.", active: true },
    { id: "jp-civil", code: "JP-CIVIL-FIX", name: "Civil Minor Repair", assetType: "FURN", departmentCode: "CIVIL", serviceCode: "CIVIL-REQ", estimatedHours: 2, priority: "LOW", steps: "Inspect defect, repair fixture and confirm user acceptance.", safetyNotes: "Use hand tools safely.", active: true },
    { id: "jp-housing", code: "JP-HSG-ROOM", name: "Housing Room Corrective Visit", assetType: "Housing", departmentCode: "HOUSING", serviceCode: "HOUSING-MAINT", estimatedHours: 3, priority: "HIGH", steps: "Inspect room asset, log condition, restore service and capture resident acceptance.", safetyNotes: "Respect occupancy protocol and isolate equipment safely.", active: true },
  ],
  housing: {
    properties: [
      { id: "hp-village", code: "HSP-001", name: "Reserve Housing Village", site: "Jazan Operations Camp", city: "Jazan", manager: "Housing Supervisor", totalRooms: 6, active: true },
      { id: "hp-annex", code: "HSP-002", name: "Reserve Staff Annex", site: "Riyadh Support Site", city: "Riyadh", manager: "Reception Team", totalRooms: 3, active: true },
    ],
    blocks: [
      { id: "hb-a", code: "HSB-A", name: "Block A", propertyId: "hp-village", floors: 3, property: { name: "Reserve Housing Village" } },
      { id: "hb-b", code: "HSB-B", name: "Block B", propertyId: "hp-village", floors: 2, property: { name: "Reserve Housing Village" } },
      { id: "hb-annex", code: "HSA-R", name: "Riyadh Annex", propertyId: "hp-annex", floors: 1, property: { name: "Reserve Staff Annex" } },
    ],
    rooms: [
      { id: "hr-a101", code: "HSR-A101", roomNumber: "A101", propertyId: "hp-village", blockId: "hb-a", floor: "1", roomType: "Single Executive", genderRestriction: "MALE", capacity: 1, occupancy: 1, status: "OCCUPIED", qrCode: "QR:HSR-A101", remarks: "Active resident room.", property: { name: "Reserve Housing Village" }, block: { name: "Block A" }, beds: [{ id: "bed-a101-1", label: "Bed 1", status: "OCCUPIED" }] },
      { id: "hr-a102", code: "HSR-A102", roomNumber: "A102", propertyId: "hp-village", blockId: "hb-a", floor: "1", roomType: "Shared Technician", genderRestriction: "MALE", capacity: 2, occupancy: 1, status: "RESERVED", qrCode: "QR:HSR-A102", remarks: "Reserved for incoming technician.", property: { name: "Reserve Housing Village" }, block: { name: "Block A" }, beds: [{ id: "bed-a102-1", label: "Bed 1", status: "RESERVED" }, { id: "bed-a102-2", label: "Bed 2", status: "AVAILABLE" }] },
      { id: "hr-a201", code: "HSR-A201", roomNumber: "A201", propertyId: "hp-village", blockId: "hb-a", floor: "2", roomType: "Shared Technician", genderRestriction: "MIXED", capacity: 2, occupancy: 0, status: "AVAILABLE", qrCode: "QR:HSR-A201", remarks: "Ready for allocation.", property: { name: "Reserve Housing Village" }, block: { name: "Block A" }, beds: [{ id: "bed-a201-1", label: "Bed 1", status: "AVAILABLE" }, { id: "bed-a201-2", label: "Bed 2", status: "AVAILABLE" }] },
      { id: "hr-a202", code: "HSR-A202", roomNumber: "A202", propertyId: "hp-village", blockId: "hb-a", floor: "2", roomType: "Isolation / Maintenance", genderRestriction: "MIXED", capacity: 1, occupancy: 0, status: "MAINTENANCE", qrCode: "QR:HSR-A202", remarks: "Blocked for bathroom repair.", property: { name: "Reserve Housing Village" }, block: { name: "Block A" }, beds: [{ id: "bed-a202-1", label: "Bed 1", status: "MAINTENANCE" }] },
      { id: "hr-b101", code: "HSR-B101", roomNumber: "B101", propertyId: "hp-village", blockId: "hb-b", floor: "1", roomType: "Female Staff", genderRestriction: "FEMALE", capacity: 2, occupancy: 2, status: "OCCUPIED", qrCode: "QR:HSR-B101", remarks: "Full room.", property: { name: "Reserve Housing Village" }, block: { name: "Block B" }, beds: [{ id: "bed-b101-1", label: "Bed 1", status: "OCCUPIED" }, { id: "bed-b101-2", label: "Bed 2", status: "OCCUPIED" }] },
      { id: "hr-r101", code: "HSR-R101", roomNumber: "R101", propertyId: "hp-annex", blockId: "hb-annex", floor: "1", roomType: "Visitor", genderRestriction: "MIXED", capacity: 1, occupancy: 0, status: "BLOCKED", qrCode: "QR:HSR-R101", remarks: "Blocked for VIP reservation.", property: { name: "Reserve Staff Annex" }, block: { name: "Riyadh Annex" }, beds: [{ id: "bed-r101-1", label: "Bed 1", status: "BLOCKED" }] },
    ],
    beds: [
      { id: "bed-a101-1", code: "HSR-A101-B1", label: "Bed 1", roomId: "hr-a101", status: "OCCUPIED", occupant: "Hamayun Ali" },
      { id: "bed-a102-1", code: "HSR-A102-B1", label: "Bed 1", roomId: "hr-a102", status: "RESERVED", occupant: "Bilal Ahmed" },
      { id: "bed-a102-2", code: "HSR-A102-B2", label: "Bed 2", roomId: "hr-a102", status: "AVAILABLE", occupant: "" },
      { id: "bed-a201-1", code: "HSR-A201-B1", label: "Bed 1", roomId: "hr-a201", status: "AVAILABLE", occupant: "" },
      { id: "bed-a201-2", code: "HSR-A201-B2", label: "Bed 2", roomId: "hr-a201", status: "AVAILABLE", occupant: "" },
      { id: "bed-a202-1", code: "HSR-A202-B1", label: "Bed 1", roomId: "hr-a202", status: "MAINTENANCE", occupant: "" },
      { id: "bed-b101-1", code: "HSR-B101-B1", label: "Bed 1", roomId: "hr-b101", status: "OCCUPIED", occupant: "Nadia Khan" },
      { id: "bed-b101-2", code: "HSR-B101-B2", label: "Bed 2", roomId: "hr-b101", status: "OCCUPIED", occupant: "Priya Menon" },
    ],
    residents: [
      { id: "res-hamayun", residentNo: "RES-00001", name: "Hamayun Ali", email: "hamayun.resident@reserve.local", phone: "+966 500000101", companyId: "RES-EMP-001", companyName: "Reserve Operations", gender: "Male", nationality: "Pakistan", departmentCode: "MEP", status: "ACTIVE" },
      { id: "res-bilal", residentNo: "RES-00002", name: "Bilal Ahmed", email: "bilal.resident@reserve.local", phone: "+966 500000102", companyId: "RES-EMP-002", companyName: "Reserve Operations", gender: "Male", nationality: "Pakistan", departmentCode: "HOUSING", status: "ACTIVE" },
      { id: "res-nadia", residentNo: "RES-00003", name: "Nadia Khan", email: "nadia.resident@reserve.local", phone: "+966 500000103", companyId: "RES-EMP-003", companyName: "Reserve Catering", gender: "Female", nationality: "India", departmentCode: "HK", status: "ACTIVE" },
      { id: "res-priya", residentNo: "RES-00004", name: "Priya Menon", email: "priya.resident@reserve.local", phone: "+966 500000104", companyId: "RES-EMP-004", companyName: "Reserve Catering", gender: "Female", nationality: "India", departmentCode: "HK", status: "ACTIVE" },
    ],
    bookings: [
      { id: "bk-00001", bookingNo: "HBK-00001", residentId: "res-hamayun", residentName: "Hamayun Ali", departmentCode: "MEP", companyName: "Reserve Operations", nationality: "Pakistan", contactNumber: "+966 500000101", gender: "Male", buildingNumber: "Block A", floorNumber: "1", roomNumber: "A101", bedNumber: "Bed 1", roomId: "hr-a101", bedId: "bed-a101-1", checkIn: dateOffset(-2), checkOut: dateOffset(28), status: "CHECKED_IN", priority: "MEDIUM", requestedBy: "Reception", approvedBy: "Housing Supervisor", approvalLevel: "Supervisor", notes: "Seed booking for end-to-end housing workflow verification.", room: { id: "hr-a101", roomNumber: "A101", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } }, bed: { label: "Bed 1" }, resident: { companyName: "Reserve Operations", nationality: "Pakistan" }, approvals: [] },
      { id: "bk-00002", bookingNo: "HBK-00002", residentId: "res-bilal", residentName: "Bilal Ahmed", departmentCode: "HOUSING", companyName: "Reserve Operations", nationality: "Pakistan", contactNumber: "+966 500000102", gender: "Male", buildingNumber: "Block A", floorNumber: "1", roomNumber: "A102", bedNumber: "Bed 1", roomId: "hr-a102", bedId: "bed-a102-1", checkIn: dateOffset(1), checkOut: dateOffset(31), status: "PENDING_APPROVAL", priority: "HIGH", requestedBy: "Housing Coordinator", approvedBy: "", approvalLevel: "Camp Manager", notes: "Pending approval for incoming technician.", room: { id: "hr-a102", roomNumber: "A102", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } }, bed: { label: "Bed 1" }, resident: { companyName: "Reserve Operations", nationality: "Pakistan" }, approvals: [] },
      { id: "bk-00003", bookingNo: "HBK-00003", residentId: "res-nadia", residentName: "Nadia Khan", departmentCode: "HK", companyName: "Reserve Catering", nationality: "India", contactNumber: "+966 500000103", gender: "Female", buildingNumber: "Block B", floorNumber: "1", roomNumber: "B101", bedNumber: "Bed 1", roomId: "hr-b101", bedId: "bed-b101-1", checkIn: dateOffset(-30), checkOut: dateOffset(2), status: "CHECKED_IN", priority: "LOW", requestedBy: "Reception", approvedBy: "Housing Supervisor", approvalLevel: "Supervisor", notes: "Upcoming check-out alert sample.", room: { id: "hr-b101", roomNumber: "B101", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block B" } }, bed: { label: "Bed 1" }, resident: { companyName: "Reserve Catering", nationality: "India" }, approvals: [] },
      { id: "bk-00004", bookingNo: "HBK-00004", residentId: "res-priya", residentName: "Priya Menon", departmentCode: "HK", companyName: "Reserve Catering", nationality: "India", contactNumber: "+966 500000104", gender: "Female", buildingNumber: "Block B", floorNumber: "1", roomNumber: "B101", bedNumber: "Bed 2", roomId: "hr-b101", bedId: "bed-b101-2", checkIn: dateOffset(-35), checkOut: dateOffset(-1), status: "CHECKED_OUT", priority: "LOW", requestedBy: "Reception", approvedBy: "Housing Supervisor", approvalLevel: "Supervisor", notes: "Closed booking for history and occupancy reports.", room: { id: "hr-b101", roomNumber: "B101", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block B" } }, bed: { label: "Bed 2" }, resident: { companyName: "Reserve Catering", nationality: "India" }, approvals: [] },
    ],
    inspections: [
      { id: "hin-00001", inspectionNo: "HIN-00001", roomId: "hr-a102", inspector: "Housing Supervisor", inspectionType: "Check-in Readiness", status: "SCHEDULED", score: 92, findings: "Verify linen, HVAC thermostat and washroom fittings before occupancy.", dueAt: dateOffset(1), room: { id: "hr-a102", roomNumber: "A102", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } } },
      { id: "hin-00002", inspectionNo: "HIN-00002", roomId: "hr-a202", inspector: "Maintenance Supervisor", inspectionType: "Bathroom Repair Follow-up", status: "FAILED", score: 62, damageFound: true, repairRequired: true, estimatedRepairCost: 850, findings: "Shower mixer still leaking; keep room out of service.", dueAt: dateOffset(0), room: { id: "hr-a202", roomNumber: "A202", floor: "2", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } } },
      { id: "hin-00003", inspectionNo: "HIN-00003", roomId: "hr-b101", inspector: "Housekeeping Lead", inspectionType: "Daily Housekeeping", status: "PASSED", score: 96, findings: "Room clean and consumables topped up.", dueAt: dateOffset(0), completedAt: dateOffset(0), room: { id: "hr-b101", roomNumber: "B101", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block B" } } },
    ],
    assets: [
      { id: "ha-bed-a101", tag: "HSA-BED-A101", name: "Executive Bed Frame", category: "Furniture", roomId: "hr-a101", status: "ACTIVE", serialNumber: "BED-A101-01", warrantyExpiry: dateOffset(365), assetValue: 1800, currentValue: 1440, depreciationRate: 10, pmSchedule: "Annual condition inspection", nextPmDue: dateOffset(180), qrCode: "QR:HSA-BED-A101", room: { roomNumber: "A101", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } } },
      { id: "ha-tv-a102", tag: "HSA-TV-A102", name: "Room Television", category: "Electronics", roomId: "hr-a102", status: "ACTIVE", serialNumber: "TV-A102-01", warrantyExpiry: dateOffset(420), assetValue: 1400, currentValue: 980, depreciationRate: 18, pmSchedule: "Quarterly function check", nextPmDue: dateOffset(45), qrCode: "QR:HSA-TV-A102", room: { roomNumber: "A102", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } } },
      { id: "ha-chair-a202", tag: "HSA-CHR-A202", name: "Desk Chair", category: "Furniture", roomId: "hr-a202", status: "DAMAGED", serialNumber: "CHR-A202-01", assetValue: 350, currentValue: 80, depreciationRate: 20, lastInspectionAt: dateOffset(-1), qrCode: "QR:HSA-CHR-A202", room: { roomNumber: "A202", floor: "2", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } } },
      { id: "ha-kettle-missing", tag: "HSA-KTL-B101", name: "Electric Kettle", category: "Appliance", roomId: "hr-b101", status: "MISSING", serialNumber: "KTL-B101-01", assetValue: 120, currentValue: 0, depreciationRate: 25, lastInspectionAt: dateOffset(-2), qrCode: "QR:HSA-KTL-B101", room: { roomNumber: "B101", floor: "1", property: { name: "Reserve Housing Village" }, block: { name: "Block B" } } },
    ],
    inventory: [
      { id: "hi-linen", sku: "HSI-LINEN-SET", name: "Linen Set", category: "Linen", description: "Complete bed linen issue set for resident rooms.", roomId: "hr-a101", storeLocation: "Housing Store / Linen Rack A", onHand: 48, minimumStock: 25, reorderPoint: 20, unit: "Set", unitCost: 42, supplierName: "Reserve Housekeeping Supplies", supplierContact: "housing.supplies@reserve.local", preferredSupplier: "Reserve Housekeeping Supplies", expiryDate: dateOffset(365), purchaseRequestStatus: "NOT_REQUIRED", lastMovementType: "RECEIPT", lastMovementQty: 48, lastMovementAt: dateOffset(-3), lastMovementBy: "System", qrCode: "QR:HSI-LINEN-SET", room: { roomNumber: "A101", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } } },
      { id: "hi-glove", sku: "HSI-PPE-GLOVE", name: "Disposable Gloves", category: "PPE items", description: "PPE gloves for housekeeping and inspection teams.", storeLocation: "Housing Store / PPE Shelf", onHand: 8, minimumStock: 20, reorderPoint: 30, unit: "Box", unitCost: 18, supplierName: "Safety First Trading", supplierContact: "+966 11 555 0201", preferredSupplier: "Safety First Trading", expiryDate: dateOffset(-5), purchaseRequestNo: "HPR-SAMPLE-001", purchaseRequestStatus: "REQUESTED", lastMovementType: "ISSUE", lastMovementQty: 4, lastMovementAt: dateOffset(-1), lastMovementBy: "Housing Supervisor", qrCode: "QR:HSI-PPE-GLOVE" },
      { id: "hi-cleaner", sku: "HSI-CLEANER-5L", name: "Multi-purpose Cleaner 5L", category: "Cleaning materials", description: "Daily cleaning chemical.", storeLocation: "Housing Store / Chemical Cabinet", onHand: 18, minimumStock: 12, reorderPoint: 16, unit: "Can", unitCost: 24, supplierName: "CleanPro", supplierContact: "+966 11 555 0202", preferredSupplier: "CleanPro", expiryDate: dateOffset(180), purchaseRequestStatus: "NOT_REQUIRED", lastMovementType: "ADJUSTMENT", lastMovementQty: 2, lastMovementAt: dateOffset(-2), lastMovementBy: "Housing Storekeeper", qrCode: "QR:HSI-CLEANER-5L" },
      { id: "hi-lamp", sku: "HSI-LAMP-LED", name: "Bedside LED Lamp", category: "Electrical spare parts", description: "Replacement lamp for resident rooms.", roomId: "hr-a102", storeLocation: "Housing Store / Electrical Shelf", onHand: 5, minimumStock: 8, reorderPoint: 10, unit: "pcs", unitCost: 65, supplierName: "BrightLine Trading", supplierContact: "+966 11 555 0203", preferredSupplier: "BrightLine Trading", expiryDate: null, purchaseRequestNo: "HPR-SAMPLE-002", purchaseRequestStatus: "APPROVED", lastMovementType: "TRANSFER", lastMovementQty: 2, lastMovementAt: dateOffset(-4), lastMovementBy: "Housing Technician", qrCode: "QR:HSI-LAMP-LED", room: { roomNumber: "A102", property: { name: "Reserve Housing Village" }, block: { name: "Block A" } } },
    ],
    approvals: [
      { id: "hap-00001", entity: "booking", entityId: "bk-00001", bookingId: "bk-00001", level: "Supervisor", step: 1, approver: "Housing Supervisor", status: "APPROVED", action: "APPROVE", approverName: "Lina Haddad", remarks: "Approved sample booking.", actedAt: dateOffset(-2), createdAt: dateOffset(-2), updatedAt: dateOffset(-2) },
      { id: "hap-00002", entity: "booking", entityId: "bk-00002", bookingId: "bk-00002", level: "Camp Manager", step: 2, approver: "Camp Manager", status: "PENDING", action: "", approverName: "", remarks: "Awaiting camp manager approval.", actedAt: null, createdAt: dateOffset(0), updatedAt: dateOffset(0) },
      { id: "hap-00003", entity: "inventory", entityId: "hi-glove", bookingId: null, level: "Store Approval", step: 1, approver: "Housing Inventory Manager", status: "WAITING", action: "", approverName: "", remarks: "Purchase request queued for PPE gloves.", actedAt: null, createdAt: dateOffset(0), updatedAt: dateOffset(0) },
    ],
    notifications: [
      { id: "hn-00001", alertType: "MAINTENANCE_DUE", channel: "SYSTEM", role: "Housing Supervisor", title: "Housing inspection due", message: "Room A102 check-in inspection is due today.", severity: "MEDIUM", recipient: "Housing Supervisor", status: "SENT", read: false, sentAt: dateOffset(0), createdAt: dateOffset(0), bookingId: "bk-00002" },
      { id: "hn-00002", alertType: "LOW_STOCK", channel: "EMAIL", role: "Housing Inventory Manager", title: "PPE stock below minimum", message: "Disposable Gloves are below minimum stock and require purchase follow-up.", severity: "HIGH", recipient: "Housing Inventory Manager", status: "SENT", read: false, sentAt: dateOffset(0), createdAt: dateOffset(0) },
      { id: "hn-00003", alertType: "UPCOMING_CHECKOUT", channel: "SYSTEM", role: "Reception Team", title: "Upcoming check-out", message: "Nadia Khan is scheduled to check out in 2 days.", severity: "LOW", recipient: "Reception Team", status: "QUEUED", read: false, sentAt: null, createdAt: dateOffset(0), bookingId: "bk-00003" },
      { id: "hn-00004", alertType: "ROOM_MAINTENANCE", channel: "SYSTEM", role: "Maintenance Supervisor", title: "Room A202 repair required", message: "Bathroom repair failed follow-up inspection. Keep room out of service.", severity: "HIGH", recipient: "Maintenance Supervisor", status: "SENT", read: false, sentAt: dateOffset(0), createdAt: dateOffset(0) },
    ],
    notificationSettings: [
      { id: "hns-checkout", alertType: "UPCOMING_CHECKOUT", label: "Upcoming check-out", enabled: true, roles: "Housing Supervisor,Reception Team", channels: "SYSTEM,EMAIL", leadDays: 3, thresholdDays: 0, severity: "MEDIUM", description: "Residents scheduled to check out soon." },
      { id: "hns-overstay", alertType: "OVERSTAY_OCCUPANT", label: "Overstay occupants", enabled: true, roles: "Housing Supervisor,Camp Manager", channels: "SYSTEM,EMAIL,SMS", leadDays: 0, thresholdDays: 1, severity: "HIGH", description: "Residents remaining after approved check-out." },
      { id: "hns-low-stock", alertType: "LOW_STOCK", label: "Low stock inventory", enabled: true, roles: "Housing Inventory Manager,Housing Supervisor", channels: "SYSTEM,EMAIL", leadDays: 0, thresholdDays: 0, severity: "MEDIUM", description: "Inventory below minimum or reorder level." },
      { id: "hns-approval", alertType: "PENDING_APPROVAL", label: "Pending approvals", enabled: true, roles: "Housing Coordinator,Housing Supervisor,Camp Manager,Reception Team", channels: "SYSTEM,EMAIL", leadDays: 0, thresholdDays: 1, severity: "MEDIUM", description: "Bookings or requests awaiting approval." },
      { id: "hns-maint", alertType: "ROOM_MAINTENANCE", label: "Room maintenance", enabled: true, roles: "Maintenance Supervisor,Housing Supervisor", channels: "SYSTEM,EMAIL", leadDays: 0, thresholdDays: 0, severity: "HIGH", description: "Rooms under repair or blocked from allocation." },
    ],
    history: [
      { id: "hh-room-a101", entity: "room", entityId: "hr-a101", roomId: "hr-a101", action: "Room seeded", actor: "System", details: "Initial room occupancy loaded.", createdAt: dateOffset(-3) },
      { id: "hh-booking-1", entity: "booking", entityId: "bk-00001", bookingId: "bk-00001", roomId: "hr-a101", action: "Booking checked in", actor: "Housing Supervisor", details: "Resident checked in and bed allocation confirmed.", createdAt: dateOffset(-2) },
      { id: "hh-booking-2", entity: "booking", entityId: "bk-00002", bookingId: "bk-00002", roomId: "hr-a102", action: "Approval requested", actor: "Housing Coordinator", details: "Incoming technician booking routed to camp manager.", createdAt: dateOffset(0) },
      { id: "hh-inspection", entity: "inspection", entityId: "hin-00002", inspectionId: "hin-00002", roomId: "hr-a202", action: "Inspection failed", actor: "Maintenance Supervisor", details: "Bathroom repair follow-up failed and repair required.", createdAt: dateOffset(0) },
      { id: "hh-inventory", entity: "inventory", entityId: "hi-glove", inventoryId: "hi-glove", action: "Low stock alert", actor: "System", details: "PPE gloves dropped below minimum stock.", createdAt: dateOffset(0) },
    ],
  },
  auditLogs: [
    { id: "audit-001", actorName: "System Administrator", role: "Admin", action: "Seeded baseline data", entity: "System", entityId: "seed", details: "Review sample data loaded across all modules.", createdAt: dateOffset(-3) },
    { id: "audit-002", actorName: "Mariam Al-Fahad", role: "Facility Director", action: "Reviewed service request", entity: "ServiceRequest", entityId: "SR-24002", details: "Critical plumbing leak moved to in-progress.", createdAt: dateOffset(-1) },
    { id: "audit-003", actorName: "Lina Haddad", role: "Supervisor", action: "Approved housing booking", entity: "HousingBooking", entityId: "HBK-00001", details: "Resident checked into room A101.", createdAt: dateOffset(-2) },
    { id: "audit-004", actorName: "Adeel Khan", role: "Technician", action: "Updated work order", entity: "WorkOrder", entityId: "WO-81024", details: "Added filter replacement progress note.", createdAt: dateOffset(0) },
  ],
};
